### PR TITLE
package.json: specify the files to include

### PR DESCRIPTION
**Pull request by XhmikosR**
```
C:\Users\xmr\Desktop\tabtab>npm pack --dry
npm notice
npm notice package: tabtab@3.0.2
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 314B   lib/constants.js
npm notice 4.9kB  lib/index.js
npm notice 12.6kB lib/installer.js
npm notice 1.9kB  lib/prompt.js
npm notice 834B   lib/scripts/bash.sh
npm notice 495B   lib/scripts/fish.sh
npm notice 391B   lib/scripts/zsh.sh
npm notice 347B   lib/utils/exists.js
npm notice 190B   lib/utils/index.js
npm notice 353B   lib/utils/systemShell.js
npm notice 822B   lib/utils/tabtabDebug.js
npm notice 1.8kB  package.json
npm notice 13.0kB readme.md
npm notice === Tarball Details ===
npm notice name:          tabtab
npm notice version:       3.0.2
npm notice filename:      tabtab-3.0.2.tgz
npm notice package size:  12.8 kB
npm notice unpacked size: 39.1 kB
npm notice shasum:        a20149aca720801ea7bab77410afb4b6e2fef47f
npm notice integrity:     sha512-lljsDGdtOy1NH[...]g7PWweneSLhAw==
npm notice total files:   14
npm notice
tabtab-3.0.2.tgz
```

Most importantly, this gets rid of `coverage` files which are currently included in the npm package, see https://packagephobia.com/result?p=tabtab

/CC @mklabs

### CODE REVIEW

**Comment by XhmikosR** [comment]
@mklabs friendly ping :)

**Comment by mklabs** [comment]
@XhmikosR Thank you ;) For both the PR and friendly reminder. Merging

I don't know when though I'll be able to push an update to npm registry. I'm in the middle of a release of a new plugin for unreal, I'll take care of other PRs for tabtab right after that and prepare a new version (might bump to 4.0)

**Comment by XhmikosR** [comment]
@mklabs thanks! I'd say, a patch release would be in place because this is a small patch and will save a lot of bytes/files for every package consumer.

The other PRs need some more work, especially the CI PR which I have no idea why it fails, but unless that's fixed I can't really test things properly :/

**Comment by mklabs** [comment]
Yeah, 4.0 if I were to include all the pending PRs right now.

**Comment by XhmikosR** [comment]
That can take a while that's why I suggested just a patch release for now.

Should be just two commands :)

**Pull request merged**
